
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserRound` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserRound
 * 
 */
export type UserRoundModel = runtime.Types.Result.DefaultSelection<Prisma.$UserRoundPayload>

export type AggregateUserRound = {
  _count: UserRoundCountAggregateOutputType | null
  _avg: UserRoundAvgAggregateOutputType | null
  _sum: UserRoundSumAggregateOutputType | null
  _min: UserRoundMinAggregateOutputType | null
  _max: UserRoundMaxAggregateOutputType | null
}

export type UserRoundAvgAggregateOutputType = {
  taps: number | null
  score: number | null
}

export type UserRoundSumAggregateOutputType = {
  taps: number | null
  score: number | null
}

export type UserRoundMinAggregateOutputType = {
  userId: string | null
  roundId: string | null
  taps: number | null
  score: number | null
}

export type UserRoundMaxAggregateOutputType = {
  userId: string | null
  roundId: string | null
  taps: number | null
  score: number | null
}

export type UserRoundCountAggregateOutputType = {
  userId: number
  roundId: number
  taps: number
  score: number
  _all: number
}


export type UserRoundAvgAggregateInputType = {
  taps?: true
  score?: true
}

export type UserRoundSumAggregateInputType = {
  taps?: true
  score?: true
}

export type UserRoundMinAggregateInputType = {
  userId?: true
  roundId?: true
  taps?: true
  score?: true
}

export type UserRoundMaxAggregateInputType = {
  userId?: true
  roundId?: true
  taps?: true
  score?: true
}

export type UserRoundCountAggregateInputType = {
  userId?: true
  roundId?: true
  taps?: true
  score?: true
  _all?: true
}

export type UserRoundAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRound to aggregate.
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRounds to fetch.
   */
  orderBy?: Prisma.UserRoundOrderByWithRelationInput | Prisma.UserRoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserRoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserRounds
  **/
  _count?: true | UserRoundCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserRoundAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserRoundSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserRoundMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserRoundMaxAggregateInputType
}

export type GetUserRoundAggregateType<T extends UserRoundAggregateArgs> = {
      [P in keyof T & keyof AggregateUserRound]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserRound[P]>
    : Prisma.GetScalarType<T[P], AggregateUserRound[P]>
}




export type UserRoundGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRoundWhereInput
  orderBy?: Prisma.UserRoundOrderByWithAggregationInput | Prisma.UserRoundOrderByWithAggregationInput[]
  by: Prisma.UserRoundScalarFieldEnum[] | Prisma.UserRoundScalarFieldEnum
  having?: Prisma.UserRoundScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserRoundCountAggregateInputType | true
  _avg?: UserRoundAvgAggregateInputType
  _sum?: UserRoundSumAggregateInputType
  _min?: UserRoundMinAggregateInputType
  _max?: UserRoundMaxAggregateInputType
}

export type UserRoundGroupByOutputType = {
  userId: string
  roundId: string
  taps: number
  score: number
  _count: UserRoundCountAggregateOutputType | null
  _avg: UserRoundAvgAggregateOutputType | null
  _sum: UserRoundSumAggregateOutputType | null
  _min: UserRoundMinAggregateOutputType | null
  _max: UserRoundMaxAggregateOutputType | null
}

type GetUserRoundGroupByPayload<T extends UserRoundGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserRoundGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserRoundGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserRoundGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserRoundGroupByOutputType[P]>
      }
    >
  >



export type UserRoundWhereInput = {
  AND?: Prisma.UserRoundWhereInput | Prisma.UserRoundWhereInput[]
  OR?: Prisma.UserRoundWhereInput[]
  NOT?: Prisma.UserRoundWhereInput | Prisma.UserRoundWhereInput[]
  userId?: Prisma.StringFilter<"UserRound"> | string
  roundId?: Prisma.StringFilter<"UserRound"> | string
  taps?: Prisma.IntFilter<"UserRound"> | number
  score?: Prisma.IntFilter<"UserRound"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  round?: Prisma.XOR<Prisma.RoundScalarRelationFilter, Prisma.RoundWhereInput>
}

export type UserRoundOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  round?: Prisma.RoundOrderByWithRelationInput
}

export type UserRoundWhereUniqueInput = Prisma.AtLeast<{
  userId_roundId?: Prisma.UserRoundUserIdRoundIdCompoundUniqueInput
  AND?: Prisma.UserRoundWhereInput | Prisma.UserRoundWhereInput[]
  OR?: Prisma.UserRoundWhereInput[]
  NOT?: Prisma.UserRoundWhereInput | Prisma.UserRoundWhereInput[]
  userId?: Prisma.StringFilter<"UserRound"> | string
  roundId?: Prisma.StringFilter<"UserRound"> | string
  taps?: Prisma.IntFilter<"UserRound"> | number
  score?: Prisma.IntFilter<"UserRound"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  round?: Prisma.XOR<Prisma.RoundScalarRelationFilter, Prisma.RoundWhereInput>
}, "userId_roundId">

export type UserRoundOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
  _count?: Prisma.UserRoundCountOrderByAggregateInput
  _avg?: Prisma.UserRoundAvgOrderByAggregateInput
  _max?: Prisma.UserRoundMaxOrderByAggregateInput
  _min?: Prisma.UserRoundMinOrderByAggregateInput
  _sum?: Prisma.UserRoundSumOrderByAggregateInput
}

export type UserRoundScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserRoundScalarWhereWithAggregatesInput | Prisma.UserRoundScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserRoundScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserRoundScalarWhereWithAggregatesInput | Prisma.UserRoundScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserRound"> | string
  roundId?: Prisma.StringWithAggregatesFilter<"UserRound"> | string
  taps?: Prisma.IntWithAggregatesFilter<"UserRound"> | number
  score?: Prisma.IntWithAggregatesFilter<"UserRound"> | number
}

export type UserRoundCreateInput = {
  taps?: number
  score?: number
  user: Prisma.UserCreateNestedOneWithoutRoundsInput
  round: Prisma.RoundCreateNestedOneWithoutUsersInput
}

export type UserRoundUncheckedCreateInput = {
  userId: string
  roundId: string
  taps?: number
  score?: number
}

export type UserRoundUpdateInput = {
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutRoundsNestedInput
  round?: Prisma.RoundUpdateOneRequiredWithoutUsersNestedInput
}

export type UserRoundUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundCreateManyInput = {
  userId: string
  roundId: string
  taps?: number
  score?: number
}

export type UserRoundUpdateManyMutationInput = {
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundListRelationFilter = {
  every?: Prisma.UserRoundWhereInput
  some?: Prisma.UserRoundWhereInput
  none?: Prisma.UserRoundWhereInput
}

export type UserRoundOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserRoundUserIdRoundIdCompoundUniqueInput = {
  userId: string
  roundId: string
}

export type UserRoundCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserRoundAvgOrderByAggregateInput = {
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserRoundMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserRoundMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  roundId?: Prisma.SortOrder
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserRoundSumOrderByAggregateInput = {
  taps?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserRoundCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput> | Prisma.UserRoundCreateWithoutUserInput[] | Prisma.UserRoundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutUserInput | Prisma.UserRoundCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserRoundCreateManyUserInputEnvelope
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
}

export type UserRoundUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput> | Prisma.UserRoundCreateWithoutUserInput[] | Prisma.UserRoundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutUserInput | Prisma.UserRoundCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserRoundCreateManyUserInputEnvelope
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
}

export type UserRoundUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput> | Prisma.UserRoundCreateWithoutUserInput[] | Prisma.UserRoundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutUserInput | Prisma.UserRoundCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserRoundUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoundUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserRoundCreateManyUserInputEnvelope
  set?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  disconnect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  delete?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  update?: Prisma.UserRoundUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoundUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserRoundUpdateManyWithWhereWithoutUserInput | Prisma.UserRoundUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
}

export type UserRoundUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput> | Prisma.UserRoundCreateWithoutUserInput[] | Prisma.UserRoundUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutUserInput | Prisma.UserRoundCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserRoundUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoundUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserRoundCreateManyUserInputEnvelope
  set?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  disconnect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  delete?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  update?: Prisma.UserRoundUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoundUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserRoundUpdateManyWithWhereWithoutUserInput | Prisma.UserRoundUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
}

export type UserRoundCreateNestedManyWithoutRoundInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput> | Prisma.UserRoundCreateWithoutRoundInput[] | Prisma.UserRoundUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutRoundInput | Prisma.UserRoundCreateOrConnectWithoutRoundInput[]
  createMany?: Prisma.UserRoundCreateManyRoundInputEnvelope
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
}

export type UserRoundUncheckedCreateNestedManyWithoutRoundInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput> | Prisma.UserRoundCreateWithoutRoundInput[] | Prisma.UserRoundUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutRoundInput | Prisma.UserRoundCreateOrConnectWithoutRoundInput[]
  createMany?: Prisma.UserRoundCreateManyRoundInputEnvelope
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
}

export type UserRoundUpdateManyWithoutRoundNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput> | Prisma.UserRoundCreateWithoutRoundInput[] | Prisma.UserRoundUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutRoundInput | Prisma.UserRoundCreateOrConnectWithoutRoundInput[]
  upsert?: Prisma.UserRoundUpsertWithWhereUniqueWithoutRoundInput | Prisma.UserRoundUpsertWithWhereUniqueWithoutRoundInput[]
  createMany?: Prisma.UserRoundCreateManyRoundInputEnvelope
  set?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  disconnect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  delete?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  update?: Prisma.UserRoundUpdateWithWhereUniqueWithoutRoundInput | Prisma.UserRoundUpdateWithWhereUniqueWithoutRoundInput[]
  updateMany?: Prisma.UserRoundUpdateManyWithWhereWithoutRoundInput | Prisma.UserRoundUpdateManyWithWhereWithoutRoundInput[]
  deleteMany?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
}

export type UserRoundUncheckedUpdateManyWithoutRoundNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput> | Prisma.UserRoundCreateWithoutRoundInput[] | Prisma.UserRoundUncheckedCreateWithoutRoundInput[]
  connectOrCreate?: Prisma.UserRoundCreateOrConnectWithoutRoundInput | Prisma.UserRoundCreateOrConnectWithoutRoundInput[]
  upsert?: Prisma.UserRoundUpsertWithWhereUniqueWithoutRoundInput | Prisma.UserRoundUpsertWithWhereUniqueWithoutRoundInput[]
  createMany?: Prisma.UserRoundCreateManyRoundInputEnvelope
  set?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  disconnect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  delete?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  connect?: Prisma.UserRoundWhereUniqueInput | Prisma.UserRoundWhereUniqueInput[]
  update?: Prisma.UserRoundUpdateWithWhereUniqueWithoutRoundInput | Prisma.UserRoundUpdateWithWhereUniqueWithoutRoundInput[]
  updateMany?: Prisma.UserRoundUpdateManyWithWhereWithoutRoundInput | Prisma.UserRoundUpdateManyWithWhereWithoutRoundInput[]
  deleteMany?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
}

export type UserRoundCreateWithoutUserInput = {
  taps?: number
  score?: number
  round: Prisma.RoundCreateNestedOneWithoutUsersInput
}

export type UserRoundUncheckedCreateWithoutUserInput = {
  roundId: string
  taps?: number
  score?: number
}

export type UserRoundCreateOrConnectWithoutUserInput = {
  where: Prisma.UserRoundWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput>
}

export type UserRoundCreateManyUserInputEnvelope = {
  data: Prisma.UserRoundCreateManyUserInput | Prisma.UserRoundCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserRoundUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoundWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoundUpdateWithoutUserInput, Prisma.UserRoundUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserRoundCreateWithoutUserInput, Prisma.UserRoundUncheckedCreateWithoutUserInput>
}

export type UserRoundUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoundWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoundUpdateWithoutUserInput, Prisma.UserRoundUncheckedUpdateWithoutUserInput>
}

export type UserRoundUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserRoundScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoundUpdateManyMutationInput, Prisma.UserRoundUncheckedUpdateManyWithoutUserInput>
}

export type UserRoundScalarWhereInput = {
  AND?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
  OR?: Prisma.UserRoundScalarWhereInput[]
  NOT?: Prisma.UserRoundScalarWhereInput | Prisma.UserRoundScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserRound"> | string
  roundId?: Prisma.StringFilter<"UserRound"> | string
  taps?: Prisma.IntFilter<"UserRound"> | number
  score?: Prisma.IntFilter<"UserRound"> | number
}

export type UserRoundCreateWithoutRoundInput = {
  taps?: number
  score?: number
  user: Prisma.UserCreateNestedOneWithoutRoundsInput
}

export type UserRoundUncheckedCreateWithoutRoundInput = {
  userId: string
  taps?: number
  score?: number
}

export type UserRoundCreateOrConnectWithoutRoundInput = {
  where: Prisma.UserRoundWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput>
}

export type UserRoundCreateManyRoundInputEnvelope = {
  data: Prisma.UserRoundCreateManyRoundInput | Prisma.UserRoundCreateManyRoundInput[]
  skipDuplicates?: boolean
}

export type UserRoundUpsertWithWhereUniqueWithoutRoundInput = {
  where: Prisma.UserRoundWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoundUpdateWithoutRoundInput, Prisma.UserRoundUncheckedUpdateWithoutRoundInput>
  create: Prisma.XOR<Prisma.UserRoundCreateWithoutRoundInput, Prisma.UserRoundUncheckedCreateWithoutRoundInput>
}

export type UserRoundUpdateWithWhereUniqueWithoutRoundInput = {
  where: Prisma.UserRoundWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoundUpdateWithoutRoundInput, Prisma.UserRoundUncheckedUpdateWithoutRoundInput>
}

export type UserRoundUpdateManyWithWhereWithoutRoundInput = {
  where: Prisma.UserRoundScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoundUpdateManyMutationInput, Prisma.UserRoundUncheckedUpdateManyWithoutRoundInput>
}

export type UserRoundCreateManyUserInput = {
  roundId: string
  taps?: number
  score?: number
}

export type UserRoundUpdateWithoutUserInput = {
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  round?: Prisma.RoundUpdateOneRequiredWithoutUsersNestedInput
}

export type UserRoundUncheckedUpdateWithoutUserInput = {
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundUncheckedUpdateManyWithoutUserInput = {
  roundId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundCreateManyRoundInput = {
  userId: string
  taps?: number
  score?: number
}

export type UserRoundUpdateWithoutRoundInput = {
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutRoundsNestedInput
}

export type UserRoundUncheckedUpdateWithoutRoundInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserRoundUncheckedUpdateManyWithoutRoundInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taps?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
}



export type UserRoundSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  roundId?: boolean
  taps?: boolean
  score?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRound"]>

export type UserRoundSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  roundId?: boolean
  taps?: boolean
  score?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRound"]>

export type UserRoundSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  roundId?: boolean
  taps?: boolean
  score?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRound"]>

export type UserRoundSelectScalar = {
  userId?: boolean
  roundId?: boolean
  taps?: boolean
  score?: boolean
}

export type UserRoundOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "roundId" | "taps" | "score", ExtArgs["result"]["userRound"]>
export type UserRoundInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}
export type UserRoundIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}
export type UserRoundIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  round?: boolean | Prisma.RoundDefaultArgs<ExtArgs>
}

export type $UserRoundPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserRound"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    round: Prisma.$RoundPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    roundId: string
    taps: number
    score: number
  }, ExtArgs["result"]["userRound"]>
  composites: {}
}

export type UserRoundGetPayload<S extends boolean | null | undefined | UserRoundDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserRoundPayload, S>

export type UserRoundCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserRoundFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserRoundCountAggregateInputType | true
  }

export interface UserRoundDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserRound'], meta: { name: 'UserRound' } }
  /**
   * Find zero or one UserRound that matches the filter.
   * @param {UserRoundFindUniqueArgs} args - Arguments to find a UserRound
   * @example
   * // Get one UserRound
   * const userRound = await prisma.userRound.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserRoundFindUniqueArgs>(args: Prisma.SelectSubset<T, UserRoundFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserRound that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserRoundFindUniqueOrThrowArgs} args - Arguments to find a UserRound
   * @example
   * // Get one UserRound
   * const userRound = await prisma.userRound.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserRoundFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserRoundFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRound that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundFindFirstArgs} args - Arguments to find a UserRound
   * @example
   * // Get one UserRound
   * const userRound = await prisma.userRound.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserRoundFindFirstArgs>(args?: Prisma.SelectSubset<T, UserRoundFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRound that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundFindFirstOrThrowArgs} args - Arguments to find a UserRound
   * @example
   * // Get one UserRound
   * const userRound = await prisma.userRound.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserRoundFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserRoundFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserRounds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserRounds
   * const userRounds = await prisma.userRound.findMany()
   * 
   * // Get first 10 UserRounds
   * const userRounds = await prisma.userRound.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userRoundWithUserIdOnly = await prisma.userRound.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserRoundFindManyArgs>(args?: Prisma.SelectSubset<T, UserRoundFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserRound.
   * @param {UserRoundCreateArgs} args - Arguments to create a UserRound.
   * @example
   * // Create one UserRound
   * const UserRound = await prisma.userRound.create({
   *   data: {
   *     // ... data to create a UserRound
   *   }
   * })
   * 
   */
  create<T extends UserRoundCreateArgs>(args: Prisma.SelectSubset<T, UserRoundCreateArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserRounds.
   * @param {UserRoundCreateManyArgs} args - Arguments to create many UserRounds.
   * @example
   * // Create many UserRounds
   * const userRound = await prisma.userRound.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserRoundCreateManyArgs>(args?: Prisma.SelectSubset<T, UserRoundCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserRounds and returns the data saved in the database.
   * @param {UserRoundCreateManyAndReturnArgs} args - Arguments to create many UserRounds.
   * @example
   * // Create many UserRounds
   * const userRound = await prisma.userRound.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserRounds and only return the `userId`
   * const userRoundWithUserIdOnly = await prisma.userRound.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserRoundCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserRoundCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserRound.
   * @param {UserRoundDeleteArgs} args - Arguments to delete one UserRound.
   * @example
   * // Delete one UserRound
   * const UserRound = await prisma.userRound.delete({
   *   where: {
   *     // ... filter to delete one UserRound
   *   }
   * })
   * 
   */
  delete<T extends UserRoundDeleteArgs>(args: Prisma.SelectSubset<T, UserRoundDeleteArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserRound.
   * @param {UserRoundUpdateArgs} args - Arguments to update one UserRound.
   * @example
   * // Update one UserRound
   * const userRound = await prisma.userRound.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserRoundUpdateArgs>(args: Prisma.SelectSubset<T, UserRoundUpdateArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserRounds.
   * @param {UserRoundDeleteManyArgs} args - Arguments to filter UserRounds to delete.
   * @example
   * // Delete a few UserRounds
   * const { count } = await prisma.userRound.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserRoundDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserRoundDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRounds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserRounds
   * const userRound = await prisma.userRound.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserRoundUpdateManyArgs>(args: Prisma.SelectSubset<T, UserRoundUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRounds and returns the data updated in the database.
   * @param {UserRoundUpdateManyAndReturnArgs} args - Arguments to update many UserRounds.
   * @example
   * // Update many UserRounds
   * const userRound = await prisma.userRound.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserRounds and only return the `userId`
   * const userRoundWithUserIdOnly = await prisma.userRound.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserRoundUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserRoundUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserRound.
   * @param {UserRoundUpsertArgs} args - Arguments to update or create a UserRound.
   * @example
   * // Update or create a UserRound
   * const userRound = await prisma.userRound.upsert({
   *   create: {
   *     // ... data to create a UserRound
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserRound we want to update
   *   }
   * })
   */
  upsert<T extends UserRoundUpsertArgs>(args: Prisma.SelectSubset<T, UserRoundUpsertArgs<ExtArgs>>): Prisma.Prisma__UserRoundClient<runtime.Types.Result.GetResult<Prisma.$UserRoundPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserRounds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundCountArgs} args - Arguments to filter UserRounds to count.
   * @example
   * // Count the number of UserRounds
   * const count = await prisma.userRound.count({
   *   where: {
   *     // ... the filter for the UserRounds we want to count
   *   }
   * })
  **/
  count<T extends UserRoundCountArgs>(
    args?: Prisma.Subset<T, UserRoundCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserRoundCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserRound.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserRoundAggregateArgs>(args: Prisma.Subset<T, UserRoundAggregateArgs>): Prisma.PrismaPromise<GetUserRoundAggregateType<T>>

  /**
   * Group by UserRound.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoundGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserRoundGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserRoundGroupByArgs['orderBy'] }
      : { orderBy?: UserRoundGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserRoundGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserRoundGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserRound model
 */
readonly fields: UserRoundFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserRound.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserRoundClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  round<T extends Prisma.RoundDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoundDefaultArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserRound model
 */
export interface UserRoundFieldRefs {
  readonly userId: Prisma.FieldRef<"UserRound", 'String'>
  readonly roundId: Prisma.FieldRef<"UserRound", 'String'>
  readonly taps: Prisma.FieldRef<"UserRound", 'Int'>
  readonly score: Prisma.FieldRef<"UserRound", 'Int'>
}
    

// Custom InputTypes
/**
 * UserRound findUnique
 */
export type UserRoundFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter, which UserRound to fetch.
   */
  where: Prisma.UserRoundWhereUniqueInput
}

/**
 * UserRound findUniqueOrThrow
 */
export type UserRoundFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter, which UserRound to fetch.
   */
  where: Prisma.UserRoundWhereUniqueInput
}

/**
 * UserRound findFirst
 */
export type UserRoundFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter, which UserRound to fetch.
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRounds to fetch.
   */
  orderBy?: Prisma.UserRoundOrderByWithRelationInput | Prisma.UserRoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRounds.
   */
  cursor?: Prisma.UserRoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRounds.
   */
  distinct?: Prisma.UserRoundScalarFieldEnum | Prisma.UserRoundScalarFieldEnum[]
}

/**
 * UserRound findFirstOrThrow
 */
export type UserRoundFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter, which UserRound to fetch.
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRounds to fetch.
   */
  orderBy?: Prisma.UserRoundOrderByWithRelationInput | Prisma.UserRoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRounds.
   */
  cursor?: Prisma.UserRoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRounds.
   */
  distinct?: Prisma.UserRoundScalarFieldEnum | Prisma.UserRoundScalarFieldEnum[]
}

/**
 * UserRound findMany
 */
export type UserRoundFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter, which UserRounds to fetch.
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRounds to fetch.
   */
  orderBy?: Prisma.UserRoundOrderByWithRelationInput | Prisma.UserRoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserRounds.
   */
  cursor?: Prisma.UserRoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRounds.
   */
  skip?: number
  distinct?: Prisma.UserRoundScalarFieldEnum | Prisma.UserRoundScalarFieldEnum[]
}

/**
 * UserRound create
 */
export type UserRoundCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * The data needed to create a UserRound.
   */
  data: Prisma.XOR<Prisma.UserRoundCreateInput, Prisma.UserRoundUncheckedCreateInput>
}

/**
 * UserRound createMany
 */
export type UserRoundCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserRounds.
   */
  data: Prisma.UserRoundCreateManyInput | Prisma.UserRoundCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserRound createManyAndReturn
 */
export type UserRoundCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * The data used to create many UserRounds.
   */
  data: Prisma.UserRoundCreateManyInput | Prisma.UserRoundCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserRound update
 */
export type UserRoundUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * The data needed to update a UserRound.
   */
  data: Prisma.XOR<Prisma.UserRoundUpdateInput, Prisma.UserRoundUncheckedUpdateInput>
  /**
   * Choose, which UserRound to update.
   */
  where: Prisma.UserRoundWhereUniqueInput
}

/**
 * UserRound updateMany
 */
export type UserRoundUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserRounds.
   */
  data: Prisma.XOR<Prisma.UserRoundUpdateManyMutationInput, Prisma.UserRoundUncheckedUpdateManyInput>
  /**
   * Filter which UserRounds to update
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * Limit how many UserRounds to update.
   */
  limit?: number
}

/**
 * UserRound updateManyAndReturn
 */
export type UserRoundUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * The data used to update UserRounds.
   */
  data: Prisma.XOR<Prisma.UserRoundUpdateManyMutationInput, Prisma.UserRoundUncheckedUpdateManyInput>
  /**
   * Filter which UserRounds to update
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * Limit how many UserRounds to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserRound upsert
 */
export type UserRoundUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * The filter to search for the UserRound to update in case it exists.
   */
  where: Prisma.UserRoundWhereUniqueInput
  /**
   * In case the UserRound found by the `where` argument doesn't exist, create a new UserRound with this data.
   */
  create: Prisma.XOR<Prisma.UserRoundCreateInput, Prisma.UserRoundUncheckedCreateInput>
  /**
   * In case the UserRound was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserRoundUpdateInput, Prisma.UserRoundUncheckedUpdateInput>
}

/**
 * UserRound delete
 */
export type UserRoundDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
  /**
   * Filter which UserRound to delete.
   */
  where: Prisma.UserRoundWhereUniqueInput
}

/**
 * UserRound deleteMany
 */
export type UserRoundDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRounds to delete
   */
  where?: Prisma.UserRoundWhereInput
  /**
   * Limit how many UserRounds to delete.
   */
  limit?: number
}

/**
 * UserRound without action
 */
export type UserRoundDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRound
   */
  select?: Prisma.UserRoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRound
   */
  omit?: Prisma.UserRoundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoundInclude<ExtArgs> | null
}
